version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps: 
      # - run: echo 'Hello world!'
      - checkout
      - run: gradle dependencies
      - run: gradle build -x test
      - run:
          name: テストの実施
          command: gradle test
